services:
  mysql:
    image: mysql:8.0
    container_name: mysqlData
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "00000"
      MYSQL_DATABASE: rissani_connect
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p00000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myyy-network

  backend:
    build:
      context: ./connect
      dockerfile: Dockerfile
    image: backend-image-rissani
    container_name: my-backend-rissani
    ports:
      - "8082:8082"
    networks:
      - myyy-network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysqlData
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "00000"
      DB_NAME: rissani_connect

  frontend:
    image: node:22-alpine
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./rissani-connect:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - myyy-network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8082/api
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

networks:
  myyy-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
